// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj0ALZ5WR-hZnXnjTZ7PElB5PSZzytEC8',
    appId: '1:476477539086:web:a81e950cb79697ffd28d5f',
    messagingSenderId: '476477539086',
    projectId: 'chito-chat-app',
    authDomain: 'chito-chat-app.firebaseapp.com',
    storageBucket: 'chito-chat-app.firebasestorage.app',
    measurementId: 'G-GP1HMF9VCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMUSeNDwyhvWNLYhIDx5RjWHietlRo3Lk',
    appId: '1:476477539086:android:dba59436d6995880d28d5f',
    messagingSenderId: '476477539086',
    projectId: 'chito-chat-app',
    storageBucket: 'chito-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6hMjqvmSiym-e946cAOXFw8LB0tAwP_E',
    appId: '1:476477539086:ios:aecdd76da44ec74bd28d5f',
    messagingSenderId: '476477539086',
    projectId: 'chito-chat-app',
    storageBucket: 'chito-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chitoChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6hMjqvmSiym-e946cAOXFw8LB0tAwP_E',
    appId: '1:476477539086:ios:aecdd76da44ec74bd28d5f',
    messagingSenderId: '476477539086',
    projectId: 'chito-chat-app',
    storageBucket: 'chito-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chitoChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj0ALZ5WR-hZnXnjTZ7PElB5PSZzytEC8',
    appId: '1:476477539086:web:85f48126a3313c72d28d5f',
    messagingSenderId: '476477539086',
    projectId: 'chito-chat-app',
    authDomain: 'chito-chat-app.firebaseapp.com',
    storageBucket: 'chito-chat-app.firebasestorage.app',
    measurementId: 'G-6T9N7CJKKX',
  );
}